version: "3.8"

services:
    frontend:
        build: ./frontend
        container_name: frontend_c
        expose:
            - "3000"
        environment:
            - NODE_ENV=production
        depends_on:
            - backend
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.rule=Host(`b.serima.se`)"
            - "traefik.http.services.frontend.loadbalancer.server.port=3000"
            - "traefik.http.routers.frontend.entrypoints=websecure"
            - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"

    backend:
        build: ./backend
        container_name: backend_c
        expose:
            - "5000"
        environment:
            - PORT=5000
            - NODE_ENV=production
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.backend.rule=Host(`najib.serima.se`)"
            - "traefik.http.services.backend.loadbalancer.server.port=5000"
            - "traefik.http.routers.backend.entrypoints=websecure"
            - "traefik.http.routers.backend.tls.certresolver=letsencrypt"

            # 🧩 CORS och headers
            - "traefik.http.middlewares.cors-header.headers.accesscontrolalloworiginlist=https://b.serima.se"
            - "traefik.http.middlewares.cors-header.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
            - "traefik.http.middlewares.cors-header.headers.accesscontrolallowheaders=Content-Type,Authorization"
            - "traefik.http.middlewares.cors-header.headers.accesscontrolallowcredentials=true"
            - "traefik.http.routers.backend.middlewares=cors-header@docker"
