version: "3.8"

services:
    frontend:
        build: ./frontend
        container_name: frontend_c
        expose:
            - "3000"
        environment:
            - NODE_ENV=production
        depends_on:
            - backend
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.frontend.rule=Host(`checkpoint.app.serima.se`)"
            - "traefik.http.routers.frontend.entrypoints=websecure"
            - "traefik.http.routers.frontend.tls.certresolver=myresolver"
            - "traefik.http.services.frontend.loadbalancer.server.port=3000"

    backend:
        build: ./backend
        container_name: backend_c
        expose:
            - "5000"
        environment:
            - PORT=5000
            - NODE_ENV=production
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.backend.rule=Host(`checkpoint.api.serima.se`)"
            - "traefik.http.routers.backend.entrypoints=websecure"
            - "traefik.http.routers.backend.tls.certresolver=myresolver"
            - "traefik.http.services.backend.loadbalancer.server.port=5000"
            - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Upgrade=websocket"
            - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Connection=Upgrade"
            - "traefik.http.routers.backend.middlewares=websocket-headers"
