version: "3.8"

services:
    frontend:
        build: ./frontend
        container_name: frontend_c
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
        depends_on:
            - backend

    backend:
        build: ./backend
        container_name: backend_c
        ports:
            - "5000:5000"
        stdin_open: true
        tty: true
        environment:
            - PORT=5000
            - NODE_ENV=production
