version: "3.8"

services:
    frontend:
        build: ./frontend
        container_name: frontend_c
        expose:
            - "3000"
        environment:
            - NODE_ENV=production
        depends_on:
            - backend

    backend:
        build: ./backend
        container_name: backend_c
        expose:
            - "5000"
        environment:
            - PORT=5000
            - NODE_ENV=production
        labels:
            - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Upgrade=websocket"
            - "traefik.http.middlewares.websocket-headers.headers.customrequestheaders.Connection=Upgrade"
