version: "3.8"

services:
    frontend:
        build: ./frontend
        container_name: frontend_c
        expose:
            - "3000"
        environment:
            - NODE_ENV=production
        depends_on:
            - backend

    backend:
        build: ./backend
        container_name: backend_c
        expose:
            - "5000"
        environment:
            - PORT=5000
            - NODE_ENV=production

    nginx:
        image: nginx:latest
        container_name: nginx_c
        volumes:
            - ./nginx/b.serima.se.conf:/etc/nginx/conf.d/default.conf
            - /etc/letsencrypt:/etc/letsencrypt:ro
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - frontend
            - backend
